### PR TITLE
aarch64: adjust SysUname - return correct machine type

### LINKED ISSUE #1325: aarch64: sys_uname
The implementation of _sys_uname_ uses hard-coded values which lead to command _uname_ to return wrong information on arm machines. The error is not critical, and I think easy to fix. I will provide a patch later.

### PR DESCRIPTION
**Pull request by chl337**
Resolve #1325.

### CODE REVIEW

File: qkernel/src/syscalls/sys_utsname.rs [hunk 1]
```diff
@@ -88,21 +88,14 @@ pub fn SysUname(task: &mut Task, args: &SyscallArguments) -> Result<i64> {
     u.Nodename[0..uts.HostName().len()].copy_from_slice(uts.HostName().as_bytes());
     u.Release[0..version.Release.len()].copy_from_slice(version.Release.as_bytes());
     u.Version[0..version.Version.len()].copy_from_slice(version.Version.as_bytes());
+    #[cfg(target_arch = "x86_64")]
     u.Machine[0.."x86_64".len()].copy_from_slice("x86_64".as_bytes());
+    #[cfg(target_arch = "aarch64")]
+    u.Machine[0.."aarch64".len()].copy_from_slice("aarch64".as_bytes());
```
Comment (shrik3) [inline qkernel/src/syscalls/sys_utsname.rs:94]: (not a comment) rust code can be really ... ugly.

**Review by shrik3 — APPROVED** [review]
