### PR TITLE
Fix paddings in signal structs

### LINKED ISSUE #1330: Issue with gvisor tests when running on ARM
Hi,

I tried to build the binary files of test of gvisor to run them on the Quark when our system is arm. The instruction is that you just need to follow [this](https://github.com/google/gvisor/tree/master/test/syscalls) instruction to build binary files of each test you want. For instance I tried to run for write syscall. So I just run
```
bazel test //test/syscalls:write_test_native
```
Then, by `bazel info bazel-bin` you can get the directory of binary files which is something like `/home/[USERNAME]/.cache/bazel/_bazel_[USERNAME]/c8d627c8e0d3a3fd49664c9d76222cd6/execroot/__main__/bazel-out/aarch64-fastbuild/bin`
Then, you just need to run `./test/syscalls/write_test_native`

Now if you do these steps on x86 and run on Quark, everything is okay and the output is:
```
+ [[ -n /htmp ]]
+ mkdir -p /htmp
+ chmod a+rwx /htmp
+ exec test/runner/runner_/runner --platform=native --platform-support=32BIT:TRUE,ALIGNMENT_CHECK:TRUE,INT3:TRUE,MULTIPROCESS:TRUE,VSYSCALL:TRUE --network=none --use-tmpfs=False --fusefs=False --file-access=exclusive --overlay=False --add-host-uds=False --add-host-connector=False --add-host-fifo=False --strace=True --debug=True --container=False --one-sandbox=True --iouring=False --directfs=False --leak-check=False --save=False --save-resume=False test/syscalls/linux/write_test
I0718 21:09:22.197586       1 main.go:170] Executing: [/gtest/test/syscalls/linux/write_test --gtest_filter=WriteTest.WriteNoExceedsRLimit]
Note: Google Test filter = WriteTest.WriteNoExceedsRLimit
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from WriteTest
[ RUN      ] WriteTest.WriteNoExceedsRLimit
[       OK ] WriteTest.WriteNoExceedsRLimit (1 ms)
[----------] 1 test from WriteTest (1 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (1 ms total)
[  PASSED  ] 1 test.
Failed to match any benchmarks against regex: .
PASS
```

But when you do it on an ARM processor, the output will be some thing like this:
```
+ [[ -n /htmp ]]
+ mkdir -p /htmp
+ chmod a+rwx /htmp
+ exec test/runner/runner_/runner --platform=native --platform-support=32BIT:TRUE,ALIGNMENT_CHECK:TRUE,INT3:TRUE,MULTIPROCESS:TRUE,VSYSCALL:TRUE --network=none --use-tmpfs=False --fusefs=False --file-access=exclusive --overlay=False --add-host-uds=False --add-host-connector=False --add-host-fifo=False --strace=True --debug=True --container=False --one-sandbox=True --iouring=False --directfs=False --leak-check=False --save=False --save-resume=False test/syscalls/linux/write_test
SIGILL: illegal instruction
PC=0x20000000 m=0 sigcode=0
```
Then it gets stuck and you need to kill quark process. (At least mine)

After some checking it seems that the issue happens when the script wants to run the `runner` in `test/runner/runner_/runner` (from [this](https://github.com/google/gvisor/blob/master/test/runner/main.go) file in gvisor test). I tried to debug it but I understood it does not even enter the main function.

Does anyone has any idea what the problem is?

### PR DESCRIPTION
**Pull request by shrik3**
should fix #1330

supersedes #1331 (the second commit is technically doing the same as 1331, but 1331 was a wrong take. The sigset should be padded to 128 bytes (i.e. adding 120 bytes padding), the problem is that the sigcontext should be padded to 16 bytes.

There is also a alignment bug in the signalstack

test wanted.

@chl337 @mhomidi

### CODE REVIEW

**Comment by chl337** [comment]
b182c089f2671aa0d16e747e02fa157be2d26d0d has skipped below the radar for quite some time:)

>test wanted
I'll try to do it later.

**Comment by shrik3** [comment]
btw, the linux source code doesn't specify the paddings explicitly, but you can certainly verify it with this cursed code:


```c
#include <signal.h>
#include <ucontext.h>
#include <stdio.h>

int main() {
	stack_t s;
	ucontext_t uc;
	printf("size of stack_t is %ld\n", sizeof(stack_t));
	printf("%ld %ld %ld\n", sizeof(s.ss_sp), sizeof(s.ss_flags), sizeof(s.ss_size));
	printf("%p %p %p\n", &s.ss_sp, &s.ss_flags, &s.ss_size );
	printf("size of ucontext %ld \n", sizeof(ucontext_t));
	printf("size of sigset %ld \n", sizeof(sigset_t));

	printf("%ld\n", (long)&(uc.uc_flags) - (long)&(uc));
	printf("%ld\n", (long)&(uc.uc_link) - (long)&(uc));
	printf("%ld\n", (long)&(uc.uc_stack) - (long)&(uc));
	printf("%ld\n", (long)&(uc.uc_sigmask) - (long)&(uc));
	printf("%ld\n", (long)&(uc.uc_mcontext) - (long)&(uc));
	return 0;
}
```

File: qlib/kernel/task.rs [hunk 1]
```diff
@@ -903,10 +903,8 @@ impl Task {
         }
 
         if !alt.IsEnable() {
-            self.signalStack = SignalStack {
-                flags: SignalStack::FLAG_DISABLE,
-                ..Default::default()
-            }
+            self.signalStack = SignalStack::default();
```
Comment (chl337) [inline qlib/kernel/task.rs:906]: Is this not äqv. to the previous implementation?

**Comment by shrik3** [comment]
On Mon Aug 26, 2024 at 1:36 PM CEST, chl337 wrote:
> @chl337 commented on this pull request.
>
>
>
> > @@ -903,10 +903,8 @@ impl Task {
>          }
>  
>          if !alt.IsEnable() {
> -            self.signalStack = SignalStack {
> -                flags: SignalStack::FLAG_DISABLE,
> -                ..Default::default()
> -            }
> +            self.signalStack = SignalStack::default();
>
> Is this not äqv. to the previous implementation?

This should be equivalent.

because the `pad` is a private field; Using `..Default::default()` on private
fields will fail to compile.

-- 
wth
220F 6A50 7BEF 8C33 3B4A 4404 99DE B3B4 1583 4AEF

**Comment by chl337** [comment]
> because the `pad` is a private field; Using `..Default::default()` on private fields will fail to compile.

I didn't know that, thanks.

**Comment by shrik3** [comment]
b182c089f2671aa0d16e747e02fa157be2d26d0d is not necessary:

since the SignalStack struct is `#[repr(C)]`, it will be aligned to 24 bytes anyways. We may just drop the first commit.

File: qlib/kernel/SignalDef.rs [hunk 2]
```diff
@@ -378,6 +378,9 @@ pub struct UContext {
     pub Stack: SignalStack,
     pub Sigset: u64,
     __pad: [u8; (1024 / 8) - core::mem::size_of::<u64>()],
+    __pad2: [u8; 8],
```
Comment (chl337) [inline qlib/kernel/SignalDef.rs:381]: It should also be initialized in [1)](https://github.com/QuarkContainer/Quark/blob/22456041cd276b4143bfb63b2fe4d3e38bfabaa6/qlib/kernel/SignalDef.rs#L389) and [2)](https://github.com/QuarkContainer/Quark/blob/22456041cd276b4143bfb63b2fe4d3e38bfabaa6/qlib/kernel/SignalDef.rs#L403).

Comment (shrik3) [reply qlib/kernel/SignalDef.rs:381]: Thanks, I'll update it.

**Review by chl337 — APPROVED** [review]
Works for me.
